### ISSUE TITLE
Fix warnings

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi#110]
All `-Werror` fail due to warnings, see lower part of:
<https://travis-ci.org/losalamos/flecsi/builds/156250814>

**Comment by junghans** [comment]
Related to #104.

**Comment by charest** [comment]
Here's the relevant error
/tmp/flecsi/build/include/flecsi/utils/static_container/meta_counter.h:39:36: error: inline function 'constexpr




--
Marc Charest
XCP-1, Los Alamos National Laboratory
charest@lanl.gov
T: 505-667-0851
________________________________

**Comment by ipdemes** [comment]
There is no really a way to get rid of the warnings in the static_container (at least I couldn't find a solution), because we are breaking some C++ assumptions there. Since we don't use it in FLeCSI anyway, should we disable it if -Werr is enabled?

Best,
Irina
