### ISSUE TITLE
Some of the Docker images on travis are messed up

### ISSUE THREAD

**Issue by charest** [losalamos/flecsi#142]
For example:

```
Error: Failed to synchronize cache for repo 'updates'

The command '/bin/sh -c dnf install -y -q openmpi-devel python-pip' returned a non-zero code: 1
```

**Comment by junghans** [comment]
If the network is down there is not much we can do....

I made a flecsi/flecsi-buildenv container, which avoids having to run dnf:
losalamos/flecsi-third-party@ae83362d65ca3ff29b823796d7756d287742eac9

**Comment by junghans** [comment]
Working on this: 2cd05bac65256d37a93d84a7f39d264e3597d558
