### ISSUE TITLE
task test is broken

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi#148]
see 8189f10b85472e408e9bd874f022b6a6af4d6a7e  and the build of it here:
https://travis-ci.org/losalamos/flecsi/jobs/173142998

**Comment by junghans** [comment]
It seems we need a check to ensure gasnet is actually build with mpi...

**Comment by ipdemes** [comment]
Sorry for not replying earlier. I am looking at this right now

**Comment by junghans** [comment]
No worries, this should fix itself, once StanfordLegion/legion#206 got merged!
