### ISSUE TITLE
fix an issue with building FLeCSI with mpich

### ISSUE THREAD

**Issue by ipdemes** [losalamos/flecsi#170]
@junghans, I would need your help with fixing an issue with building ThirdParties+FLeCSI using MPICH.
For some reason " " - fPIC" " flag is added  with the quotation marks on the sides to the FLeCSI  compile FLAGS. I guess it comes from the GASNET build, but I might be wrong. 

./CMakeFiles/dual.dir/flags.make:CXX_FLAGS =  -std=c++14 -g   " -fPIC"

**Comment by junghans** [comment]
We add `-fPIC` here:
https://github.com/losalamos/flecsi-third-party/blob/master/cmake/gasnet.cmake#L18
but without quotes!

Does you legion version incl. StanfordLegion/legion@0093143476bd3cb3546e545469243801dcca2f9d?
(see https://github.com/StanfordLegion/legion/pull/206#issuecomment-258952445)

**Comment by ipdemes** [comment]
I know. So where does it come from? I built legion with ThirdParty, and assume this commit should be there.

**Comment by junghans** [comment]
Yes, it is part of what is in third-party, I just checked.

**Comment by junghans** [comment]
I made a mpich buildenv: losalamos/flecsi-buildenv@664d9c54eebefa91395beeedb58f15b18673f548

**Comment by ipdemes** [comment]
So, do you have an idea how to get rid of the quotes?

**Comment by junghans** [comment]
Ok, I build losalamos/flecsi-third-party@c3f49c84bdeb758d06373f517297401dbf3b408a
and got a successful build: https://travis-ci.org/losalamos/flecsi-third-party/jobs/181742159.

Can you give me some detail how you arrived at the above issue? Which branch of flecsi are you building?

**Comment by ipdemes** [comment]
I am just building execution branch in Flecsi with mpilegion runtime.  
Are you here today? If so I can stop by your office and show..

**Comment by junghans** [comment]
Found it too: https://travis-ci.org/losalamos/flecsi-third-party/jobs/181769632#L1619

**Comment by junghans** [comment]
@ipdemes: please test that fix!

**Comment by ipdemes** [comment]
@junghans, thank you! This commit fixed an error.
