### ISSUE TITLE
Burton test blessed file

### ISSUE THREAD

**Issue by tuxfan** [losalamos/flecsi#34]
This test depends on the particular order of entries of a std::map, which doesn't seem to be consistent across runs.  We need a more robust test that doesn't depend on the specific order of the storage mechanism (this is arbitrary).

**Comment by junghans** [comment]
Hotfix in 859edeb80598d7b3caaeadf38afb1e899f6eb486, revert when this issue is fixed.

**Comment by wohlbier** [comment]
Fixed.
