### ISSUE TITLE
mesh_graph_partition::partition is NOT vtxdist in ParMetis

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#41]
If the goal of `mesh::compute_graph_partition()` is to generate the Distributed CSR format as in ParMetis, the current implementation of  `mesh_graph_partition::partition` member is wrong. The current implementation lists the number of elements in each partition instead of the indices to the "global" sequence of the elements. For example, partitioning the Sagittarius mesh of 4 cells into two equal partitions, the `mesh_graph_partition::partition` should be `[0, 2, 4]` instead of `[0, 2, 2]` as currently implemented.

**Comment by ollielo** [comment]
If we agree that this is indeed an issue, the correct implementation is just a prefix sum away.

**Comment by junghans** [comment]
Fixed in 76e85007f1b3d02c4511b9151ebbc713bdbcf781

@ollielo: Please use `(fixes #XX)` in the commit message, next time.

**Comment by ollielo** [comment]
Sure.
