### ISSUE TITLE
add support for system-provided tpl

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi#42]
Most third party libraries dependencies are actually dependencies of [exodusii](http://sourceforge.net/projects/exodusii/), e.g. hdf5, zlib, netcdf.

We currently use static libraries, which make things a bit harder (see losalamos/cinch#9), switching to shared libraries will make this much easier.

**Comment by charest** [comment]
shared libraries are a pain when you have to cross compile.  Are we sure we want to go this route?

**Comment by junghans** [comment]
Cross-compiling is always a pain, mainly because cmake doesn't support it natively, and I don't see how shared libraries would make that worse. If you cross-compile all the dependencies have to be cross-compiled as well, shared libraries don't change that requirement nor lift it. However, static libraries have no dependencies information embedded and hence when linking a static libraries in an executable one has to link against all its dependencies as well, which can be very tedious, e.g. how would you know if a certain libhdf5 is build with or without bzip support and hence you have to link bizp in or not. Shared libraries on the other hand have dependencies information embedded.

And where would you see the need for cross-compiling at this stage? Aren't most performance related cross-compiling cases covered by icc's `-ax` option these days?

**Comment by charest** [comment]
OK you win

**Comment by ollielo** [comment]
Two questions:

1. Does commit [c431b2d](https://github.com/junghans/flecsi/commit/c431b2de1dd8942e1f8516ffb2308f01ca821960) make flecsi_third_part uncessary?
2. Where do FindMETIS.cmake and FindSCOTCH.cmake come from? A fresh install from Metis source tar ball does not provide the FindMETIS.cmake file, either does .rpm files on Fedora/RHEL. Does this only work with APT based systems?

**Comment by junghans** [comment]
1.) It mainly allows to use system-provided libraries and not just flecsi_third_part. My longer term plan is to change flecsi_third_part in way that we can use `CMAKE_PREFIX_PATH` and the normal `find_package(XXX)` to detect system as well as flecsi_third_part.
2.) FindMETIS.cmake and FindSCOTCH.cmake are written by me following: https://cmake.org/Wiki/CMake:How_To_Find_Libraries#Writing_find_modules. They should work on most distributions.
