### ISSUE TITLE
ASSERT_DEATH in zip.cc

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#44]
What is the purpose of ASSERT_DEATH in the zip.cc? Is it expecting the test program to crash? 

On my system, if I compile it with Release or RelWithDebInfo, the test program does not crash:

>  /home/ollie/git/flecsi/flecsi/utils/test/zip.cc:52: Failure
>  Death test: zip(a, b, c_fail)
>  Result: failed to die.
>  Error msg:

Is this the correct behavior or not?

**Comment by charest** [comment]
As per gtest documentation, yes it is
