### ISSUE TITLE
Action to small??

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#49]
There is a mysterious warning message saying some enum class is to small:

 `flecsi/Build/include/flecsi/tree/tree_topology.h:1092:20: warning: ‘flecsi::tree_topology_dev::tree_branch<long unsigned int, 2ul>::action_’ is too small to hold all values of ‘enum class flecsi::tree_topology_dev::action’
   action action_ : 2;`

What is that about? Can it be change to some larger number?

**Comment by junghans** [comment]
I would like to add a `-Werror` build travis, so we should fix that!

/cc @ddaniel

**Comment by nickm319** [comment]
Fixed.
