### ISSUE TITLE
FindMetis can not find suitable libmetis from TPL

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#50]
FindMetis.cmake in [fbc362d](https://github.com/losalamos/flecsi/commit/fbc362d0b3ea29a7bcb65e3b53caef139ed1eacb#diff-6ffe21967dd148427fedcd66f7492c94) does not think the libmetis.a from TPL is suitable.

```
-- Checking for module 'metis'
--   Package 'metis' not found
-- Could NOT find METIS: Found unsuitable version "/opt/flecsi_third_party/lib/libmetis.a", but required is at least "5.1" (found /opt/flecsi_third_party/lib/libmetis.a)
```

However, the header file does identify itself as version 5.1.0
```
[ollie@salami Build]$ grep METIS_VER /opt/flecsi_third_party/include/metis.h 
#define METIS_VER_MAJOR         5
#define METIS_VER_MINOR         1
#define METIS_VER_SUBMINOR      0
```

**Comment by junghans** [comment]
Fixed in losalamos/flecsi@05d5cb03385cb14b9200c42e1a37a2667819c012
