### ISSUE TITLE
Fresh clone appears to fail

### ISSUE THREAD

**Issue by cmsquared** [losalamos/flecsi#52]
Fresh clone fails because of what appears to be relative paths to submodules if one follows the README.md:

    cmalone@varan:~/code$ git clone --recursive git@github.com:flecsi/flecsi.git flecsi-la
    Cloning into 'flecsi-la'...a': git clone --recursive git@github.com:flecsi/flecsi
    remote: Counting objects: 6079, done.
    remote: Compressing objects: 100% (99/99), done.
    remote: Total 6079 (delta 45), reused 0 (delta 0), pack-reused 5980
    Receiving objects: 100% (6079/6079), 2.54 MiB | 1.60 MiB/s, done.
    Resolving deltas: 100% (4292/4292), done.
    Checking connectivity... done.
    Submodule 'cinch' (git@github.com:flecsi/cinch.git) registered for path 'cinch'
    Cloning into 'cinch'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    fatal: clone of 'git@github.com:flecsi/cinch.git' into submodule path 'cinch' failed

If instead one clones from `losalamos/flecsi.git`, which is the _real_ repository, then you get things correct.  Either the README.md needs updated, or the relative paths need updated.

Also note, my fork fails in the same way, effectively rendering it useless unless I go in and manually change the submodule location - or I recursively make forks of all the submodules - neither of which I should need to do...

    Cloning into 'cinch'...
    ERROR: Repository not found.
    fatal: Could not read from remote repository.
    
    Please make sure you have the correct access rights
    and the repository exists.
    fatal: clone of 'git@github.com:cmsquared/cinch.git' into submodule path 'cinch' failed

**Comment by charest** [comment]
The repository moved some time ago, it is currently here


git clone --recursive git@github.com:losalamos/flecsi.git


That link should work.  I guess the flecsi/flecsi.git symlink is broken.


As for your fork.  Either change the relative path in .gitmodules to point to

git@github.com:losalamos/cinch.git or fork cinch too.


--
Marc Charest
XCP-1, Los Alamos National Laboratory
charest@lanl.gov
T: 505-667-0851
________________________________

**Comment by cmsquared** [comment]
Right, I can go in and fix the submodule manually or fork that as well, but I shouldn't have to :)

**Comment by charest** [comment]
Theres pros and cons to everything


http://blog.tremily.us/posts/Relative_submodules/


--
Marc Charest
XCP-1, Los Alamos National Laboratory
charest@lanl.gov
T: 505-667-0851
________________________________

**Comment by junghans** [comment]
@charest: Yep, that is why I have my own cinch fork ;-) However, all flecsi team member can use branches instead of forks to work around that issue.
