### ISSUE TITLE
CMAKE_PREFIX_PATH ignored for ExodusII and LAPACKE

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#54]
If the goal of recent changes to project.cmake and packages.cmake is to use CMAKE_PREFIX_PATH instead of TPL_INSTALL_PREFIX, the cmake rules for linking to ExodusII and LAPACKE should also be changed accordingly. Otherwise, the dependencies are not linked.

```
$ grep TPL_INSTALL_PREFIX *
packages.cmake:  if(EXISTS ${TPL_INSTALL_PREFIX}/include/exodusII.h
packages.cmake:     AND EXISTS ${TPL_INSTALL_PREFIX}/lib/libexodus.a)
packages.cmake:    set(IO_LIBRARIES ${TPL_INSTALL_PREFIX}/lib/libexodus.a
packages.cmake:      ${TPL_INSTALL_PREFIX}/lib/libnetcdf.a
packages.cmake:      ${TPL_INSTALL_PREFIX}/lib/libhdf5_hl.a
packages.cmake:      ${TPL_INSTALL_PREFIX}/lib/libhdf5.a
packages.cmake:      ${TPL_INSTALL_PREFIX}/lib/libszip.a
packages.cmake:      ${TPL_INSTALL_PREFIX}/lib/libz.a
packages.cmake:    include_directories( ${TPL_INSTALL_PREFIX}/include )
packages.cmake:  if(EXISTS ${TPL_INSTALL_PREFIX}/include/lapacke.h
packages.cmake:     AND EXISTS ${TPL_INSTALL_PREFIX}/lib/liblapacke.a)
packages.cmake:    include_directories(${TPL_INSTALL_PREFIX}/include)
packages.cmake:          ${TPL_INSTALL_PREFIX}/lib/liblapacke.a
packages.cmake:          ${TPL_INSTALL_PREFIX}/lib/liblapack.a
packages.cmake:          ${TPL_INSTALL_PREFIX}/lib/libblas.a
project.cmake:set( TPL_INSTALL_PREFIX ""
project.cmake:if (NOT TPL_INSTALL_PREFIX STREQUAL "")
project.cmake:  message(WARNING "TPL_INSTALL_PREFIX is obsolete, use CMAKE_PREFIX_PATH instead (and rebuild the latest version third-party libraries)")
project.cmake:  list(APPEND CMAKE_PREFIX_PATH "${TPL_INSTALL_PREFIX}")
```

**Comment by junghans** [comment]
`CMAKE_PREFIX_PATH` is handled internally by cmake's `find_package()` and if you look into `packages.cmake` you will see that there are corresponding find_package calls for LAPACKE and ExodusII. The remaining appearances of `TPL_INSTALL_PREFIX` will be removed soon. The main reason I haven't done that yet is to keep backwards compatibility for a week or two and hence give the developers some time to switch to a version of flecsi-third-party using shared libraries (losalamos/flecsi-third-party@316b6c3e4bf9f24631375845ebf20521bb43f65f or later).

**Comment by ollielo** [comment]
O.K. I installed the new TPL as shared library. However, why isn't there .so for Scotch?

```
 ls /opt/flecsi_third_party_shared/lib/
cmake             libhdf5_hl.so.10.0.1  libhdf5.so.10.0.1   libnetcdf.so        libscotcherr.a      libszip.so.2.1
libexodus.so      libhdf5_hl.so.1.8.15  libhdf5.so.1.8.15   libnetcdf.so.7      libscotcherrexit.a  libz.so
libexoIIv2for.so  libhdf5.settings      libmetis.so         libnetcdf.so.7.2.1  libscotchmetis.a    libz.so.1.2
libhdf5_hl.so     libhdf5.so            libnetcdf.settings  libscotch.a         libszip.so          pkgconfig
```

It also have some problems with pthread library while linking:

```
[ 63%] Linking CXX executable test/partition/partition
/usr/bin/cmake -E cmake_link_script CMakeFiles/partition.dir/link.txt --verbose=1
/usr/lib64/ccache/c++    -std=c++14 -g   CMakeFiles/partition.dir/flecsi/partition/test/partition.cc.o CMakeFiles/partition.dir/cinch/gtest-auxiliary/gtest-standard.cc.o  -o test/partition/partition -rdynamic /opt/flecsi_third_party_shared/lib/libmetis.so /opt/flecsi_third_party_shared/lib/libscotch.a /opt/flecsi_third_party_shared/lib/libscotcherr.a lib/libflecsi.a -lgtest -Wl,-rpath,/opt/flecsi_third_party_shared/lib 
/usr/bin/ld: /opt/flecsi_third_party_shared/lib/libscotch.a(common_thread.o): undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/partition.dir/build.make:125: recipe for target 'test/partition/partition' failed

```

**Comment by junghans** [comment]
libscotch's buildsystem does not support shared libraries! (For metis there is a fix: losalamos/flecsi-third-party@109aabccfe982da84eecddf796d36b9e602c4bf5). The build works on traivs: https://travis-ci.org/losalamos/flecsi/jobs/126268141, but your error hints towards that you have compiled your `libscotch.a` using a newer glibc than the one you are currently running. Try rebuilding everything on the same node, if the problem persists open a separate issue for it.

**Comment by ollielo** [comment]
I think the reason is that neither findSCOTCH.cmake nor package.cmake adds the pthread library as one of the denpendent library. Thus it is not linked at all. If I added the library in, it works. Can you make some change in either one of the .cmake files?

```
$ git diff
diff --git a/cinch b/cinch
index 5572b6f..1fee169 160000
--- a/cinch
+++ b/cinch
@@ -1 +1 @@
-Subproject commit 5572b6f50aaf6fe2be897e88c042cac191459a3d
+Subproject commit 1fee169d5c675cb106883c100c6004ed38ebff76
diff --git a/flecsi/partition/CMakeLists.txt b/flecsi/partition/CMakeLists.txt
index 1923760..83c52d5 100644
--- a/flecsi/partition/CMakeLists.txt
+++ b/flecsi/partition/CMakeLists.txt
@@ -28,7 +28,7 @@ cinch_add_unit(partition
   INPUTS  test/metis_mesh.blessed 
           test/metis.blessed 
           test/scotch.blessed
-  LIBRARIES     ${PARTITION_LIBRARIES} flecsi
+  LIBRARIES     ${PARTITION_LIBRARIES} flecsi pthread
 )
 endif()
```

**Comment by junghans** [comment]
Ah, I see. This is another problem of static libraries! We should really try to compile scotch shared instead. Can you test my workaround below?

**Comment by ollielo** [comment]
It works, go ahead and merge it to the master.

**Comment by junghans** [comment]
Please keep issue open until the patch is actually merged.

On a second thought, I think this is not the right solution. libscotch depends on libz as well, so it is just a matter of time until this check will break again. (The error currently doesn't show as libexodus pulls in libz as well.)

The right solution is to incorporate this [fix](http://anonscm.debian.org/cgit/debian-science/packages/scotch.git/tree/debian/patches/build-fixes.patch) from debian or the cmake build system from OpenCMISS-Dependencies/scotch@70af7bc836bb964145528cf6a9f8d007c09628cb, which both allow to build libscotch shared.
