### ISSUE TITLE
Use std::queue instead of home make queue out of new-ed array.

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#77]
Both ext_queue and legion_queue in `legion_handshake.h` should use `std::queue` instead of the home made queue implementation.

**Comment by ipdemes** [comment]
OK, I'll look at this. Thank you, Ollie

**Comment by ipdemes** [comment]
Ok. I've look at std::queue and would argue on the sufficiency of it's implementation for the handshake needs. The main advantage of the Legion's Event is that it was specifically created for queueing Legion tasks and have some additional methadata necessary for the tasks. In additional, it taking care of possible thread conflicts. So I believe that queue implementation in legion_handshake can't be replaced with std::queue.

**Comment by ipdemes** [comment]
So, I will close the issue, but feel free to reopen it if you disagree with above.
