### ISSUE TITLE
Race condition in legion_handshake.h

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#78]
Both `ext_queue` and `legion_queue` are shared and accessed by various methods in `ExtLegionHandshake` and may be modified under multiple thread contexts without any proper synchronization. A race condition is highly likely.

**Comment by ipdemes** [comment]
Since our queue implementation is based on the Legion's "UserEvent", which is taking care of race conditions" (see implementation of the Event class in the legion's "runtime/realm/event.h" file)  I close an issue.
Please feel free to reopen it if you disagree.
