### ISSUE TITLE
id_t crazyness

### ISSUE THREAD

**Issue by ollielo** [losalamos/flecsi#93]
@nickm319 

Due to C++'s intricate rules on integral type, bit field and implicit conversion, mangling and messing around with them is never a good idea. However, our current id_t and thus a large part of the topological computation is based on this. This practice does not only confuses human but also diminishes the job compiler is doing (i.e. type checking).

Here is an example in `mesh_topology_t::compute_graph_partition()`

```
   for(size_t from_id = 0; from_id < n; ++from_id){
      auto to_ids = id_range(c1.get_entities(), fv1[from_id], fv1[from_id + 1]);
      cp.offset.push_back(offset);
      
      for(auto to_id : to_ids){
        auto ret_ids = id_range(c2.get_entities(), fv2[to_id], fv2[to_id + 1]);
        
        for(auto ret_id : ret_ids){
          if(ret_id != from_id){
            cp.index.push_back(ret_id);
            ++offset;
          }
        }
      }
      ...
   }
```

Here we mix size_t and id_t and do comparison on them.  Can you tell under what condition  `if (ret_id != from_id)` will work as expected? **Hint, there is a bug in it**.

**Comment by charest** [comment]
I am confused, thats obviously a bug comparing local to global ids?  What are you getting at or advocating?

**Comment by ollielo** [comment]
One of them is what you just mentioned. It is a bug comparing local to global ids but **in what sense? How are we going to fix it?** The answer may be obvious to you but is not so obvious for other people. I would say it was not too obvious to @nickm319 when he wrote this. 

The deeper questions are why didn't compiler catch this earlier? Why didn't some unit tests catch this?

**Comment by charest** [comment]
I think you want something like ret_id.entity() != from_id

**Comment by ollielo** [comment]
Sort of. 

If I tell you that the code as is works *sometimes*, do you believe me? When are the *sometimes*?

**Comment by nickm319** [comment]
I'm almost done fixing it.

**Comment by ollielo** [comment]
What I would like to see is a rethinking and overhaul of the design and implementation of `id_t` but I also understand it would be a large scale change at this point.

**Comment by nickm319** [comment]
I removed the implicit conversion from global id to size_t. While this did provide some convenience and solve some problems, I agree that safety and type checking is more important. I am not sure exactly what you had in mind to improve this by overhauling it. It is very important that our id's remain word-sized, in 64 bits we need to pack in domain, dimension, partition, local id, and now flags. If you have a specific way to improve on this while keeping these requirements, please let me know.

Nick

**Comment by ollielo** [comment]
I don't have an exact idea yet.

However, as you found out, there are more bugs than the one @charest found in the original code. The `to_id` when used as an index to `fv2` will be automatically converted to a very large number when `dim != 0` or `domain != 0`. `fv2[to_id]` silently fails and return some nonsense value that happens to work out just right for certain conditions. I wonder if there are any other places such "happens to work" happens.

BTW, if you want to make sure the total number of bits is 64, why don't you say so but use `sizeof(size_t)` in `static_assert`?
```
    static_assert(PBITS + EBITS + FBITS == sizeof(size_t) * 8 - 4, 
                  "invalid id bit configuration");
```

All these questions are begging another question:

**Is it really that important to cram all these information into a fixed 64-bits thing? How much do we allow this constraint to distort our other design decisions?**

**Comment by ollielo** [comment]
To clarify, removing the implicit conversion from `id_t` to `size_t` is definitely a right direction to begin with.

**Comment by nickm319** [comment]
Ollie,

Ok, I'm glad we fixed that, nice catch. There were some other places throughout the code where we were using id_t when it should have been size_t and this change uncovered them. Since id_t is used everywhere in the mesh storage, it seems like this is an important space optimization. Maybe we could test other implementations of id_t that don't do the bit twiddling and see if there is a good enough performance reason not to do it this way. Since id_t is well encapsulated, we could just quickly create an alternate one that doesn't do this, but we are storing 5 distinct fields so the mesh connectivity and such will require significantly more storage and test how it effects the performance of mesh building, traversal, etc.

Nick

**Comment by ollielo** [comment]
@nickm319 

In [daa4cbc](https://github.com/losalamos/flecsi/commit/316f7116eadc3a2fb5da7a09635d70fd5cee3281), you still missed `if (ret_it.entity() != from_id)` at `mesh_topology.h:1722`. Strangely enough, it still compiles while we supposed to have removed id_t -> size_t conversion. Did you miss something somewhere else as well?

**Comment by nickm319** [comment]
Maybe if I add explicit to the id_t constructors...

**Comment by nickm319** [comment]
Yes, that was in fact the problem, the size_t ctor is now explicit.

From: First name Last name <nickm@lanl.gov<mailto:nickm@lanl.gov>>
Date: Thursday, June 16, 2016 at 8:20 AM
To: losalamos/flecsi <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [losalamos/flecsi] id_t crazyness (#93)

Maybe if I add explicit to the id_t constructors...

**Comment by nickm319** [comment]
I also changed it so that to convert to size_t, it just does an reinterpret cast. So there is less bit splicing, which should happen mostly in building the mesh. I think this is fine now, unless you want to look into it further, like testing performance w/o bit fields, but I think beeing able to fit everything into 64 bits is a good thing. Glad we talked about it.

**Comment by ollielo** [comment]
@nickm319 

As for reinterpret_case<>, can you tell me which bits are high order bits:

```
    size_t entity_ : EBITS;
    size_t partition_ : PBITS;
    size_t flags_ : FBITS;
    size_t domain_ : 2;
    size_t dimension_ : 2;
```

**Comment by nickm319** [comment]
dimension_ is the highest bits

**Comment by ollielo** [comment]
Thanks.
